---
title: "casos de covid nas últinas 24 horas dezembro "
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bg: "#5c2cca"
      fg: "#5757b1" 
      primary: "#5c2cca"
      navbar-bg: "#13173C"
      base_font: 
        google: Prompt
      heading_font:
        google: Sen
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: JetBrains Mono
          local: false

    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
rm(list = ls())
library(flexdashboard)
library(tidyverse)
library(ggspatial)
library(esquisse)

library(ggplot2)
library(dplyr)
library(viridis)
library(gt)
library(geobr)
library(sf)
library(maptools)
library(leaflet)
library(plotly)
library(shiny)
library(shiny)
library(ggplot2)
library(ggthemes)
library(plotly)
library(gapminder)
library(ggplot2)
library(gganimate)

library(animation)


library(geobr)

library(dplyr)
library(ggplot2)
library(tidyverse)
library(ggspatial)
library(esquisse)


covid2<-list.files(path = "C:/Users/josef/Documents/covidhj/",
                   pattern = "*.csv", 
                   full.names = T) %>% 
  map_df(~read_csv2(., col_types = cols(.default = "c"))) %>% filter(regiao!="Brasil")



ontem<- covid2 %>% 
  filter((data=="2021-12-01")) %>%  rename(abbrev_state=estado)

ontem$casosNovos<-as.numeric(ontem$casosNovos)
####### chamando os estados do brasil 


brasil<-read_state(code_state = "all")



####### unindo os data frames 
juntos1<-full_join(brasil,ontem,by="abbrev_state")

###########convertendo casos novos para numeriico 

juntos1$casosNovos<-as.numeric(juntos1$casosNovos)

######### função para somar os casos de covid 

teste1<-aggregate(juntos1$casosNovos/2, by=list(Estados=juntos1$name_state), FUN=sum)
sum(teste1$x)
## ordenando  os data frames 
teste1 <-teste1 %>% arrange(teste1$Estados)
brasil<-brasil %>% arrange(brasil$name_state)


###criando as variaveiis pra juntar 
teste1$custid<-seq(1:27)

brasil$custid<-seq(1:27)

juntos2<-full_join(brasil,teste1,by="custid")

colnames(juntos2)[8]<-"casos"
juntos2$casos<-as.numeric(juntos2$casos)


#### criando  a categoria 


juntos2$categoria<-cut(juntos2$casos,breaks=c(0,50,200,400,600,800,1000,Inf),
                       labels=c(" 1 a 50","51 a 200","201 a 400",
                 "401 a 600","601 a 800","801 a 1000","mais de 1000"))


coord_pontos2 <- juntos2%>% 
  mutate(juntos2$casos) %>% 
  st_centroid()

```

Column {data-width=500}
-----------------------------------------------------------------------

### mapa dos casos novos de covid 02/12/2021

```{r}


p<- ggplot(juntos2)+geom_sf(aes(fill=categoria))+
  geom_sf(data = coord_pontos2, aes(size = casos), col = "red", alpha = .55,
          show.legend = FALSE) +
  scale_fill_manual(values = c('#d7d7e3','#EBE5AD','#b7ac48','#d5df20','#d8a527','#f4920b','#fa6005'
  ))+
  annotation_scale(location= "br", height =  unit(0.2,"cm"))+
  annotation_north_arrow(location= "tr",style = north_arrow_nautical, height = unit(1.5, "cm"), width = unit(1.5, "cm")) +
  labs( title = "novos casos Covid-19\nConfirmados nas últimas 24 hrs",
        #subtitle = "Casos \nConfirmados nas últimas 24 hrs",
        x=NULL,
        y=NULL) +
  theme_bw() + 
  theme(legend.position = c(0.18,0.2),
        legend.key.size = unit(4,"mm"))




library(plotly)


ggplotly(p)




```





Column {data-width=500}
-----------------------------------------------------------------------


###  Registro



```{r}
library(DT)

le<-data.frame(teste1$Estados,teste1$x)
colnames(le)[1]<-"Estados"
colnames(le)[2]<-"Casos Novos Registrados "

le%>% datatable()


``` 